openapi: 3.0.0
info:
  title: API Restfull con JSON:API Spect
  description: Api con datos de proyectos, alumnos y profesores
  version: 0.1.9
servers:
  - url: http://proyectosdwa.es/manuel/api_proyectos
    description: Ubicada en el servidor de proyectos dwa
  - url: http://localhost:8000/api
    description: Desarrollo en local
paths:
  /projects:
    get:
      summary: Obtener lista de proyectos
      responses:
        '200':
  /teachers:
    get:
      summary: Obtener lista de profesores
      responses:
        '200':
          description: Éxito
  /users:
    get:
      summary: Obtener lista de usuarios
      responses:
        '200':
          description: Éxito
  /projects/{id}:
    get:
      summary: Obtener detalles de un proyecto
      parameters:
        - in: path
          name: id
          required: true
          description: ID del proyecto
          schema:
            type: integer
      responses:
        '200':
          description: Éxito
  /teachers/{id}:
    get:
      summary: Obtener detalles de un profesor
      parameters:
        - in: path
          name: id
          required: true
          description: ID del profesor
          schema:
            type: integer
      responses:
        '200':
          description: Éxito
  /users/{id}:
    get:
      summary: Obtener detalles de un usuario
      parameters:
        - in: path
          name: id
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Éxito
    /user:
    post:
        summary: Descripción de la operación POST
        description: Agrega un nuevo recurso al sistema
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: object
                properties:
                  teacher:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID del profesor
                      nombre:
                        type: string
                        description: Nombre del profesor
                      email:
                        type: string
                        format: email
                        description: Email del profesor
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: ID del usuario
                      name:
                        type: string
                        description: Nombre del usuario
                      email:
                        type: string
                        format: email
                        description: Email del usuario
                      password:
                        type: string
                        format: password
                        description: Contraseña del usuario
                      password_confirmation:
                        type: string
                        format: password
                        description: Confirmación de la contraseña
                  project:
                    type: object
                    properties:
                      titulo:
                        type: string
                        description: Título del proyecto
                      horas:
                        type: integer
                        description: Horas dedicadas al proyecto
                      web:
                        type: string
                        format: uri
                        description: URL del sitio web del proyecto
                      user_id:
                        type: integer
                        description: ID del usuario asociado al proyecto
                      teacher_id:
                        type: integer
                        description: ID del profesor asociado al proyecto
        responses:
          '200':
            description: Recurso creado exitosamente
          '400':
            description: Petición inválida

    put:
      summary: Actualizar un usuario
      parameters:
        - in: path
          name: id
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Éxito
    delete:
      summary: Eliminar un alumno
      parameters:
        - in: path
          name: id
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '204':
          description: No Content
